main:
  web_trigger_builder:
    - name: droid-ddk-builder
      runner:
        cpus: 4
      git:
        enable: true
        lfs: false
      services:
        - docker
      stages:
        - name: docker build
          script: |
            apt update && apt install -y jq make --no-install-recommends
            make -C docker builder PUSH=1 REG=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
